export const BOOK_CATEGORIES: string[] = [
    'Fantasy',
    'Sci-Fi',
    'Dystopian',
    'Adventure',
    'Romance',
    'Mystery',
    'Horror',
    'Thriller & Suspense',
    'Historical Fiction',
    'Romance',
    'Contemporary Fiction',
    'Literary Fiction',
    'Magical Realism',
    'Biography',
    'Food & Drink',
    'History',
    'Travel',
    'True Crime',
    'Science & Technology',
    'Business and economics',
    'Health and fitness',
    'Humor',
    'Philosophy',
    'Fairytale',
    'Satire',
    'Western',
]

